const Config = require("../config");
const fs = require("fs");
const {
  Insta,
  pinterest,
  adultvid,
  hentai,
  tlang,
  botpic,
  language,
  getString,
  wikimedia,
  toAudio,
  toPTT,
  toVideo,
  sync,
  syncgit,
  ffmpeg,
  TelegraPh,
  UploadFileUgu,
  webp2mp4File,
  fancy,
  randomfancy,
  ringtone,
  styletext,
  isAdmin,
  isBotAdmin,
  createUrl,
  mediafireDl,
  mediafire,
  dare,
  truth,
  random_question,
  amount_of_questions
} = require("./scraper");
const acrcloud = require(__dirname + "/class/init");
const {
  unixTimestampSecond,
  generateMessageTag,
  processTime,
  getBuffer,
  smdBuffer,
  fetchJson,
  smdJson,
  runtime,
  clockString,
  sleep,
  isUrl,
  getTime,
  formatDate,
  formatp,
  jsonformat,
  logic,
  generateProfilePicture,
  bytesToSize,
  getSizeMedia,
  parseMention,
  GIFBufferToVideoBuffer,
  smsg,
  callsg
} = require("./serialized");
const {
  listall,
  strikeThrough,
  wingdings,
  vaporwave,
  typewriter,
  analucia,
  tildeStrikeThrough,
  underline,
  doubleUnderline,
  slashThrough,
  sparrow,
  heartsBetween,
  arrowBelow,
  crossAboveBelow,
  creepify,
  bubbles,
  mirror,
  squares,
  roundsquares,
  flip,
  tiny,
  createMap,
  serif_I,
  manga,
  ladybug,
  runes,
  serif_B,
  serif_BI,
  fancy1,
  fancy2,
  fancy3,
  fancy4,
  fancy5,
  fancy6,
  fancy7,
  fancy8,
  fancy9,
  fancy10,
  fancy11,
  fancy12,
  fancy13,
  fancy14,
  fancy15,
  fancy16,
  fancy17,
  fancy18,
  fancy19,
  fancy20,
  fancy21,
  fancy22,
  fancy23,
  fancy24,
  fancy25,
  fancy26,
  fancy27,
  fancy28,
  fancy29,
  fancy30,
  fancy31,
  fancy32,
  fancy33,
  randomStyle
} = require("./stylish-font");
const {
  sck1
} = require(__dirname + "/database/user");
const {
  sck
} = require(__dirname + "/database/group");
const {
  alive
} = require(__dirname + "/database/alive");
const {
  pg,
  dbs,
  groupdb,
  userdb,
  alivedb,
  bot_
} = require(__dirname + "/schemes");
const {
  cmd,
  smd,
  commands
} = require(__dirname + "/plugins");
const {
  thumbPath,
  sendAnimeReaction,
  yt,
  sendGImages,
  AudioToBlackVideo,
  textToLogoGenerator,
  photoEditor,
  updateProfilePicture,
  randomeFunfacts,
  getRandom,
  generateSticker,
  forwardMessage,
  plugins,
  audioEditor,
  send,
  react,
  note,
  sendWelcome,
  aitts
} = require("./suhail.js");
module.exports = {
  yt: yt,
  plugins: plugins,
  forwardMessage: forwardMessage,
  updateProfilePicture: updateProfilePicture,
  thumbPath: thumbPath,
  sendAnimeReaction: sendAnimeReaction,
  sendGImages: sendGImages,
  textToLogoGenerator: textToLogoGenerator,
  photoEditor: photoEditor,
  updateProfilePicture: updateProfilePicture,
  randomeFunfacts: randomeFunfacts,
  AudioToBlackVideo: AudioToBlackVideo,
  getRandom: getRandom,
  generateSticker: generateSticker,
  audioEditor: audioEditor,
  send: send,
  react: react,
  note: note,
  sendWelcome: sendWelcome,
  aitts: aitts,
  pg: pg,
  dbs: dbs,
  bot_: bot_,
  alive: alive,
  sck: sck,
  smd: smd,
  commands: commands,
  sck1: sck1,
  Insta: Insta,
  pinterest: pinterest,
  adultvid: adultvid,
  hentai: hentai,
  tlang: tlang,
  botpic: botpic,
  language: language,
  getString: getString,
  wikimedia: wikimedia,
  toAudio: toAudio,
  toPTT: toPTT,
  toVideo: toVideo,
  sync: sync,
  syncgit: syncgit,
  ffmpeg: ffmpeg,
  TelegraPh: TelegraPh,
  UploadFileUgu: UploadFileUgu,
  webp2mp4File: webp2mp4File,
  fancy: fancy,
  randomfancy: randomfancy,
  ringtone: ringtone,
  styletext: styletext,
  isAdmin: isAdmin,
  isBotAdmin: isBotAdmin,
  createUrl: createUrl,
  mediafireDl: mediafireDl,
  mediafire: mediafire,
  dare: dare,
  truth: truth,
  random_question: random_question,
  amount_of_questions: amount_of_questions,
  unixTimestampSecond: unixTimestampSecond,
  generateMessageTag: generateMessageTag,
  processTime: processTime,
  getBuffer: getBuffer,
  smdBuffer: smdBuffer,
  fetchJson: fetchJson,
  smdJson: smdJson,
  runtime: runtime,
  clockString: clockString,
  sleep: sleep,
  isUrl: isUrl,
  getTime: getTime,
  formatDate: formatDate,
  formatp: formatp,
  jsonformat: jsonformat,
  logic: logic,
  generateProfilePicture: generateProfilePicture,
  bytesToSize: bytesToSize,
  getSizeMedia: getSizeMedia,
  parseMention: parseMention,
  GIFBufferToVideoBuffer: GIFBufferToVideoBuffer,
  smsg: smsg,
  callsg: callsg,
  pinterest: pinterest,
  tlang: tlang,
  botpic: botpic,
  language: language,
  getString: getString,
  wikimedia: wikimedia,
  toAudio: toAudio,
  toPTT: toPTT,
  toVideo: toVideo,
  sync: sync,
  syncgit: syncgit,
  ffmpeg: ffmpeg,
  TelegraPh: TelegraPh,
  UploadFileUgu: UploadFileUgu,
  webp2mp4File: webp2mp4File,
  fancy: fancy,
  randomfancy: randomfancy,
  listall: listall,
  strikeThrough: strikeThrough,
  wingdings: wingdings,
  vaporwave: vaporwave,
  typewriter: typewriter,
  analucia: analucia,
  tildeStrikeThrough: tildeStrikeThrough,
  underline: underline,
  doubleUnderline: doubleUnderline,
  slashThrough: slashThrough,
  sparrow: sparrow,
  heartsBetween: heartsBetween,
  arrowBelow: arrowBelow,
  crossAboveBelow: crossAboveBelow,
  creepify: creepify,
  bubbles: bubbles,
  mirror: mirror,
  squares: squares,
  roundsquares: roundsquares,
  flip: flip,
  tiny: tiny,
  createMap: createMap,
  serif_I: serif_I,
  manga: manga,
  ladybug: ladybug,
  runes: runes,
  serif_B: serif_B,
  serif_BI: serif_BI,
  serif_I: serif_I,
  fancy1: fancy1,
  fancy2: fancy2,
  fancy3: fancy3,
  fancy4: fancy4,
  fancy5: fancy5,
  fancy6: fancy6,
  fancy7: fancy7,
  fancy8: fancy8,
  fancy9: fancy9,
  fancy10: fancy10,
  fancy11: fancy11,
  fancy12: fancy12,
  fancy13: fancy13,
  fancy14: fancy14,
  fancy15: fancy15,
  fancy16: fancy16,
  fancy17: fancy17,
  fancy18: fancy18,
  fancy19: fancy19,
  fancy20: fancy20,
  fancy21: fancy21,
  fancy22: fancy22,
  fancy23: fancy23,
  fancy24: fancy24,
  fancy25: fancy25,
  fancy26: fancy26,
  fancy27: fancy27,
  fancy28: fancy28,
  fancy29: fancy29,
  fancy30: fancy30,
  fancy31: fancy31,
  fancy32: fancy32,
  fancy33: fancy33,
  randomStyle: randomStyle,
  Insta: Insta,
  addCommand: cmd,
  groupdb: groupdb,
  userdb: userdb,
  alivedb: alivedb,
  prefix: Config.HANDLERS.includes("null") ? "" : Config.HANDLERS[0],
  Config: Config,
  setting: Config,
  stor: async () => {
    return require("./sqlite-store.js").snapshot();
  },
  fancytext: (text, index) => {
    index = index - 1;
    return listall(text)[index];
  },
  parsedJid: (text = "") => {
    return text.match(/[0-9]+(-[0-9]+|)(@g.us|@s.whatsapp.net)/g) || [];
  },
  
  lidMap: require("./lid.js"),
  getAdmin: async (sock, ctx) => {
    const metadata = await sock.groupMetadata(ctx.chat);
    
    const a = [];
    const lidMap = require("./lid.js");
    for (const participant of metadata.participants || []) {
      if (participant.admin == null) {
        continue;
      }
      a.push(participant.jid || lidMap.resolve(participant.id) || participant.id);
    }
    return a;
  },
  isGroup: isGroup = jid => {
    return jid.endsWith("@g.us");
  },
  parseurl: parseurl = url => {
    return url.match(new RegExp(/https?:\/\/(www\.)?[-a-zA-Z0-9@:%._+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_+.~#?&/=]*)/, "gi"));
  },
  isInstaUrl: url => {
    /(?:(?:http|https):\/\/)?(?:www.)?(?:instagram.com|instagr.am|instagr.com)\/(\w+)/gim.test(url);
  },
  isNumber: function isNumber() {
    const num = parseInt(this);
    return typeof num === "number" && !isNaN(num);
  },
  shazam: async function shazam(audioBuffer) {
    let acr = new acrcloud({
      host: "identify-eu-west-1.acrcloud.com",
      endpoint: "/v1/identify",
      signature_version: "1",
      data_type: "audio",
      secure: true,
      access_key: "c816ad50a2bd6282e07b90447d93c38c",
      access_secret: "ZpYSwmCFpRovcSQBCFCe1KArX7xt8DTkYx2XKiIP"
    });
    let response = await acr.identify(audioBuffer);
    let {
      code: code,
      msg: msg
    } = response.status;
    if (code !== 0) {
      return msg;
    }
    let {
      title: title,
      artists: artists,
      album: album,
      genres: genres,
      release_date: releaseDate,
      external_metadata: externalMetadata
    } = response.metadata.music[0];
    let {
      youtube: youtube,
      spotify: spotify
    } = externalMetadata;
    return {
      status: 200,
      title: title,
      artists: artists !== undefined ? artists.map(item => item.name).join(", ") : "",
      genres: genres !== undefined ? genres.map(item => item.name).join(", ") : "",
      release_date: releaseDate,
      album: album.name || "",
      data: response
    };
  }
};
